# Generated by Django 5.2.7 on 2025-10-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0005_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nota',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
