# Generated by Django 5.0.4 on 2025-10-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0007_contratosolicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosolicitacao',
            name='contrato_final',
            field=models.FileField(blank=True, null=True, upload_to='contratos/finais/'),
        ),
    ]
