# Generated by Django 5.0.4 on 2025-10-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0008_contratosolicitacao_contrato_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosolicitacao',
            name='contrato_assinado',
            field=models.FileField(blank=True, null=True, upload_to='contratos/assinados/'),
        ),
    ]
