# Generated by Django 5.0.4 on 2025-11-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0009_contratosolicitacao_contrato_assinado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosolicitacao',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contratosolicitacao',
            name='mp_payment_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contratosolicitacao',
            name='primeiro_aluguel_pago',
            field=models.BooleanField(default=False),
        ),
    ]
