# Generated by Django 5.0.4 on 2025-10-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_imovel_foto_imovel_usuario_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
